Colours = require("Alienocean.palette").Get()
Highlights = {}
---@return table
Highlights.build = function()
	local opts = require("Alienocean").opts
	local theme = {
		Normal = { fg = Colours.fg, bg = Colours.bg },
		FzfLuaBorder = { link = "Normal" },
		FzfLuaNormal = { link = "Normal" },
		NvimSpacing = { link = "Normal" },
		javaScript = { link = "Normal" },
		lessVariableValue = { link = "Normal" },
		["@variable.parameter"] = { link = "Normal" },
		BlinkCmpDoc = { fg = Colours.yellow, bg = Colours.bgdark },
		BlinkCmpDocBorder = { fg = Colours.purple, bg = Colours.bgdark },
		BlinkCmpDocSeparator = { fg = Colours.purple, bg = Colours.bgdark },
		BlinkCmpKind = { link = "Normal" },
		BlinkCmpKindText = { link = "Normal" },
		BlinkCmpKindClass = { link = "BlinkCmpKindText" },
		BlinkCmpKindColor = { link = "BlinkCmpKindText" },
		BlinkCmpKindConstant = { link = "BlinkCmpKindText" },
		BlinkCmpKindConstructor = { link = "BlinkCmpKindText" },
		BlinkCmpKindEnum = { link = "BlinkCmpKindText" },
		BlinkCmpKindEnumMember = { link = "BlinkCmpKindText" },
		BlinkCmpKindEvent = { link = "BlinkCmpKindText" },
		BlinkCmpKindField = { link = "BlinkCmpKindText" },
		BlinkCmpKindFile = { link = "BlinkCmpKindText" },
		BlinkCmpKindFolder = { link = "BlinkCmpKindText" },
		BlinkCmpKindFunction = { link = "BlinkCmpKindText" },
		BlinkCmpKindInterface = { link = "BlinkCmpKindText" },
		BlinkCmpKindKeyword = { link = "BlinkCmpKindText" },
		BlinkCmpKindMethod = { link = "BlinkCmpKindText" },
		BlinkCmpKindModule = { link = "BlinkCmpKindText" },
		BlinkCmpKindOperator = { link = "BlinkCmpKindText" },
		BlinkCmpKindProperty = { link = "BlinkCmpKindText" },
		BlinkCmpKindReference = { link = "BlinkCmpKindText" },
		BlinkCmpKindSnippet = { link = "BlinkCmpKindText" },
		BlinkCmpKindStruct = { link = "BlinkCmpKindText" },
		BlinkCmpKindTypeParameter = { link = "BlinkCmpKindText" },
		BlinkCmpKindUnit = { link = "BlinkCmpKindText" },
		BlinkCmpKindValue = { link = "BlinkCmpKindText" },
		BlinkCmpKindVariable = { link = "BlinkCmpKindText" },
		BlinkCmpLabel = { fg = Colours.purple },
		BlinkCmpLabelMatch = { fg = Colours.yellow },
		BlinkCmpMenu = { fg = Colours.yellow, bg = Colours.bgdark },
		BlinkCmpSignatureHelp = { fg = Colours.yellow },
		Boolean = { fg = Colours.green },
		["@boolean"] = { link = "Boolean" },
		["@character"] = { link = "Character" },
		["@string.escape"] = { link = "Character" },
		["@string.special.path"] = { link = "Character" },
		CmpItemAbbrDeprecated = { fg = Colours.red },
		CmpItemAbbrMatch = { fg = Colours.green },
		CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
		CmpItemKindFunction = { fg = Colours.cyan },
		CmpItemKindMethod = { link = "CmpItemKindFunction" },
		CmpItemKindKeyword = { fg = Colours.fg },
		CmpItemKindProperty = { link = "CmpItemKindKeyword" },
		CmpItemKindUnit = { link = "CmpItemKindKeyword" },
		CmpItemKindText = { fg = Colours.fg },
		CmpItemKindVariable = { fg = Colours.yellow },
		CmpItemKindInterface = { link = "CmpItemKindVariable" },
		ColorColumn = { bg = Colours.pink },
		Comment = { fg = Colours.pink, bg = Colours.bg },
		CtrlPLinePre = { link = "Comment" },
		LspCodeLens = { link = "Comment" },
		helpSectionDelim = { link = "Comment" },
		["@comment"] = { link = "Comment" },
		["@lsp.type.comment"] = { link = "Comment" },
		["@string.docstrings"] = { link = "Comment" },
		["@text.literal"] = { link = "Comment" },
		["@keyword.conditional"] = { link = "Conditional" },
		["@keyword.conditional.ternary"] = { link = "Conditional" },
		Constant = { fg = Colours.fg },
		Character = { link = "Constant" },
		TelescopeResultsConstant = { link = "Constant" },
		TelescopeResultsStruct = { link = "Constant" },
		rubyConstant = { link = "Constant" },
		vimHiAttrib = { link = "Constant" },
		["@attribute"] = { link = "Constant" },
		["@constant"] = { link = "Constant" },
		["@lsp.type.enumMember"] = { link = "Constant" },
		Cursor = { fg = Colours.fg, bg = Colours.cyan },
		FzfLuaCursor = { link = "Cursor" },
		CursorColumn = { bg = Colours.bg },
		CursorLine = { bg = Colours.bg },
		FzfLuaCursorLine = { link = "CursorLine" },
		CursorLineNr = { fg = Colours.green, bg = Colours.bg, bold = opts.allowTextStyling },
		FzfLuaCursorLineNr = { link = "CursorLineNr" },
		["@keyword.debug"] = { link = "Debug" },
		["@constant.macro"] = { link = "Define" },
		Delimiter = { fg = Colours.yellow },
		NvimArrow = { link = "Delimiter" },
		NvimColon = { link = "Delimiter" },
		NvimComma = { link = "Delimiter" },
		NvimParenthesis = { link = "Delimiter" },
		Operator = { link = "Delimiter" },
		javaScriptBraces = { link = "Delimiter" },
		markdownLinkDelimiter = { link = "Delimiter" },
		markdownURLDelimiter = { link = "Delimiter" },
		vimContinue = { link = "Delimiter" },
		vimSetSep = { link = "Delimiter" },
		["@punctuation"] = { link = "Delimiter" },
		["@punctuation.bracket"] = { link = "Delimiter" },
		["@punctuation.special"] = { link = "Delimiter" },
		DiagnosticDeprecated = { sp = Colours.purple, strikethrough = opts.allowTextStyling },
		DiagnosticHint = { fg = Colours.purple, bg= Colours.bgdark },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticHintFloating = { fg = Colours.green },
		DiagnosticInfo = { fg = Colours.purple },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticOk = { fg = Colours.green },
		DiagnosticFloatingOk = { link = "DiagnosticOk" },
		DiagnosticSignOk = { link = "DiagnosticOk" },
		DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
		DiagnosticSignError = { fg = Colours.red, bg = Colours.bgdark },
		DiagnosticSignHint = { fg = Colours.purple, bg = Colours.bgdark },
		DiagnosticSignInfo = { fg = Colours.purple, bg = Colours.bgdark },
		DiagnosticSignWarn = { fg = Colours.purple, bg = Colours.bgdark },
		DiagnosticUnderlineError = { underline = opts.allowTextStyling },
		DiagnosticUnderlineHint = { underline = opts.allowTextStyling },
		DiagnosticUnderlineInfo = { underline = opts.allowTextStyling },
		DiagnosticUnderlineOk = { underline = opts.allowTextStyling },
		DiagnosticUnderlineWarn = { underline = opts.allowTextStyling },
		DiagnosticUnnecessary = { fg = Colours.fg, underline = opts.allowTextStyling },
		DiagnosticVirtualTextError = { fg = Colours.red, bg = Colours.bgdark },
		DiagnosticVirtualTextHint = { fg = Colours.green, bg = Colours.bgdark },
		DiagnosticVirtualTextInfo = { fg = Colours.green, bg = Colours.bgdark },
		DiagnosticVirtualTextWarn = { fg = Colours.purple, bg = Colours.bgdark },
		DiagnosticVirtualTextWarning = { fg = Colours.cyan },
		DiagnosticWarn = { fg = Colours.purple },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticWarning = { fg = Colours.yellow },
		DiagnosticFloatingWarning = { link = "DiagnosticWarning" },
		DiagnosticWarningFloating = { fg = Colours.red },
		DiffAdd = { fg = Colours.fg, bg = Colours.green },
		["@diff.plus"] = { link = "DiffAdd" },
		["@text.diff.add"] = { link = "DiffAdd" },
		DiffAdded = { fg = Colours.cyan, bg = Colours.green },
		DiffChange = { fg = Colours.fg, bg = Colours.purple },
		["@diff.delta"] = { link = "DiffChange" },
		DiffDelete = { fg = Colours.red, bg = Colours.bgdark, bold = opts.allowTextStyling },
		["@diff.minus"] = { link = "DiffDelete" },
		["@text.diff.delete"] = { link = "DiffDelete" },
		DiffRemoved = { fg = Colours.fg, bg = Colours.yellow },
		DiffText = { fg = Colours.fg, bg = Colours.cyan, bold = opts.allowTextStyling },
		Directory = { fg = Colours.green, bg = Colours.bgdark },
		gitCommitFile = { link = "Directory" },
		ErrorMsg = { fg = Colours.red, bg = Colours.purple },
		DiagnosticError = { link = "ErrorMsg" },
		DiagnosticErrorFloating = { link = "ErrorMsg" },
		DiagnosticFloatingError = { link = "ErrorMsg" },
		Error = { link = "ErrorMsg" },
		LazyReasonRuntime = { link = "ErrorMsg" },
		LazyTaskError = { link = "ErrorMsg" },
		NvimFigureBrace = { link = "ErrorMsg" },
		NvimInternalError = { link = "ErrorMsg" },
		NvimInvalid = { link = "ErrorMsg" },
		NvimInvalidSingleQuotedUnknownEscape = { link = "ErrorMsg" },
		NvimInvalidSpacing = { link = "ErrorMsg" },
		NvimSingleQuotedUnknownEscape = { link = "ErrorMsg" },
		["@comment.error"] = { link = "ErrorMsg" },
		["@keyword.exception"] = { link = "Exception" },
		["@number.float"] = { link = "Float" },
		FloatBorder = { fg = Colours.yellow, bg = Colours.bgdark },
		LspBorderBG = { link = "FloatBorder" },
		FloatShadow = { bg = Colours.bgdark },
		FloatShadowThrough = { bg = Colours.bgdark },
		FoldColumn = { fg = Colours.fg, bg = Colours.bgdark },
		CursorLineFold = { link = "FoldColumn" },
		Folded = { fg = Colours.pink, bg = Colours.bgdark },
		Function = { fg = Colours.yellow },
		TelescopeResultsFunction = { link = "Function" },
		["@function"] = { link = "Function" },
		["@function.call"] = { link = "Function" },
		["@function.method"] = { link = "Function" },
		["@function.method.call"] = { link = "Function" },
		["@lsp.type.decorator"] = { link = "Function" },
		["@lsp.type.function"] = { link = "Function" },
		["@lsp.type.method"] = { link = "Function" },
		["@method"] = { link = "Function" },
		GitSignsAdd = { fg = Colours.green, bg = Colours.bgdark },
		GitSignsChange = { fg = Colours.yellow, bg = Colours.bgdark },
		GitSignsDelete = { fg = Colours.red, bg = Colours.bgdark },
		IblIndent = { fg = Colours.fg, nocombine = true },
		IblScope = { fg = Colours.bgdark, nocombine = true },
		IblWhitespace = { fg = Colours.green, nocombine = true },
		Identifier = { fg = Colours.fg },
		NvimIdentifier = { link = "Identifier" },
		TelescopeResultsIdentifier = { link = "Identifier" },
		rubyLocalVariableOrMethod = { link = "Identifier" },
		["@attribute.builtin"] = { link = "Identifier" },
		["@field"] = { link = "Identifier" },
		["@lsp.type.parameter"] = { link = "Identifier" },
		["@lsp.type.variable"] = { link = "Identifier" },
		["@markup.math"] = { link = "Identifier" },
		["@namespace"] = { link = "Identifier" },
		["@parameter"] = { link = "Identifier" },
		["@string.special.symbol"] = { link = "Identifier" },
		["@tag.attribute"] = { link = "Identifier" },
		["@text.reference"] = { link = "Identifier" },
		["@variable"] = { link = "Identifier" },
		["@variable.builtin"] = { link = "Identifier" },
		["@variable.parameter.builtin"] = { link = "Identifier" },
		Ignore = { fg = Colours.pink, underline = opts.allowTextStyling },
		Conceal = { link = "Ignore" },
		IncSearch = { fg = Colours.fg, bg = Colours.purple },
		FzfLuaSearch = { link = "IncSearch" },
		["@keyword.lua"] = { link = "Include" },
		["@tag.delimiter"] = { link = "Include" },
		PreProc = { link = "Keyword" },
		["@keyword"] = { link = "Keyword" },
		["@keyword.coroutine"] = { link = "Keyword" },
		["@keyword.function"] = { link = "Keyword" },
		["@keyword.import"] = { link = "Keyword" },
		["@keyword.modifier"] = { link = "Keyword" },
		["@keyword.modifier.ruby"] = { link = "Keyword" },
		["@keyword.operator"] = { link = "Keyword" },
		["@keyword.return"] = { link = "Keyword" },
		["@keyword.type"] = { link = "Keyword" },
		["@keyword.vim"] = { link = "Keyword" },
		["@preproc"] = { link = "Keyword" },
		["@label"] = { link = "Label" },
		LazyButton = { bg = Colours.bgdark },
		LazyButtonActive = { fg = Colours.fg, bg = Colours.bgdark },
		MasonHeaderSecondary = { link = "LazyButtonActive" },
		LazyComment = {},
		LazyCommit = {},
		LazyCommitIssue = { bg = Colours.bgdark },
		LazyCommitScope = { bg = Colours.bgdark },
		LazyCommitType = { bg = Colours.bgdark },
		LazyDimmed = {},
		LazyDir = {},
		LazyH1 = { fg = Colours.green, bg = Colours.bgdark },
		MasonHighlightBlockBold = { link = "LazyH1" },
		LazyH2 = { fg = Colours.yellow, bg = Colours.bgdark },
		MasonHighlightBlock = { link = "LazyH2" },
		LazyLocal = {},
		LazyNoCond = {},
		LazyNormal = { bg = Colours.bgdark },
		MasonNormal = { link = "LazyNormal" },
		LazyProgressDone = {},
		LazyProgressTodo = {},
		LazyProp = { bg = Colours.bgdark },
		LazyReasonCmd = {},
		LazyReasonEvent = {},
		LazyReasonFt = { bg = Colours.bgdark },
		LazyReasonImport = {},
		LazyReasonKeys = {},
		LazyReasonPlugin = {},
		LazyReasonSource = {},
		LazyReasonStart = {},
		LazyTaskOutput = { bg = Colours.bgdark },
		LazyUrl = { bg = Colours.bgdark },
		LazyValue = {},
		LineNr = { fg = Colours.fg, bg = Colours.bgdark },
		LineNrAbove = { link = "LineNr" },
		LineNrBelow = { link = "LineNr" },
		TelescopeResultsLineNr = { link = "LineNr" },
		LspFloatWinNormal = { fg = Colours.purple, bg = Colours.bgdark },
		LspReferenceRead = {
			fg = Colours.green,
			sp = Colours.purple,
			bold = opts.allowTextStyling,
			undercurl = opts.allowTextStyling,
		},
		LspReferenceText = {
			fg = Colours.green,
			bg = Colours.bgdark,
			sp = Colours.purple,
			bold = opts.allowTextStyling,
			undercurl = opts.allowTextStyling,
		},
		LspReferenceWrite = {
			fg = Colours.green,
			sp = Colours.purple,
			bold = opts.allowTextStyling,
			undercurl = opts.allowTextStyling,
		},
		LspSignatureActiveParameter = {
			sp = Colours.purple,
			bold = opts.allowTextStyling,
			italic = opts.allowTextStyling,
			underline = opts.allowTextStyling,
		},
		BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
		["@function.macro"] = { link = "Macro" },
		MasonError = {},
		MasonHeader = { fg = Colours.green, bg = Colours.bgdark },
		MasonHeading = {},
		MasonHighlight = { fg = Colours.green, bg = Colours.bgdark },
		MasonMutedBlockBold = { link = "MasonHighlight" },
		MasonHighlightBlockBoldSecondary = {},
		MasonHighlightBlockSecondary = {},
		MasonHighlightSecondary = {},
		MasonMuted = { fg = Colours.green, bg = Colours.bgdark },
		MasonMutedBlock = { link = "MasonMuted" },
		MasonWarning = {},
		MatchParen = { fg = Colours.yellow, bold = opts.allowTextStyling, underline = opts.allowTextStyling },
		ModeMsg = { bold = opts.allowTextStyling },
		MoreMsg = { fg = Colours.green, bold = opts.allowTextStyling },
		NERDTreeHelp = { fg = Colours.purple, bg = Colours.bg },
		NonText = { fg = Colours.fg, bg = "none", bold = opts.allowTextStyling },
		BlinkCmpGhostText = { link = "NonText" },
		BlinkCmpLabelDeprecated = { link = "NonText" },
		EndOfBuffer = { link = "NonText" },
		Whitespace = { link = "NonText" },
		markdownCodeDelimiter = { link = "NonText" },
		markdownHeadingRule = { link = "NonText" },
		BlinkCmpSignatureHelpBorder = { link = "NormalFloat" },
		Number = { fg = Colours.green },
		Float = { link = "Number" },
		NvimNumber = { link = "Number" },
		rubyInstanceVariable = { link = "Number" },
		["@number"] = { link = "Number" },
		TelescopeResultsOperator = { link = "Operator" },
		["@operator"] = { link = "Operator" },
		Pmenu = { fg = Colours.fg, bg = Colours.bgdark },
		BlinkCmpMenuBorder = { link = "Pmenu" },
		NormalFloat = { link = "Pmenu" },
		PmenuExtra = { link = "Pmenu" },
		BlinkCmpLabelDescription = { link = "PmenuExtra" },
		BlinkCmpLabelDetail = { link = "PmenuExtra" },
		BlinkCmpSource = { link = "PmenuExtra" },
		PmenuKind = { fg = Colours.cyan },
		PmenuSbar = { bg = Colours.fg },
		BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
		FzfLuaScrollFloatEmpty = { link = "PmenuSbar" },
		PmenuSel = { fg = Colours.fg, bg = Colours.bgdark },
		BlinkCmpMenuSelection = { link = "PmenuSel" },
		PmenuExtraSel = { link = "PmenuSel" },
		PmenuKindSel = { link = "PmenuSel" },
		PmenuThumb = { fg = Colours.fg, bg = Colours.bgdark },
		BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
		FzfLuaScrollFloatFull = { link = "PmenuThumb" },
		Define = { link = "PreProc" },
		Include = { link = "PreProc" },
		Macro = { link = "PreProc" },
		PreCondit = { link = "PreProc" },
		Question = { fg = Colours.green, bold = opts.allowTextStyling },
		RedrawDebugClear = { fg = Colours.fg, bg = Colours.yellow },
		RedrawDebugComposed = { fg = Colours.fg, bg = Colours.cyan },
		RedrawDebugNormal = { reverse = true },
		RedrawDebugRecompose = { fg = Colours.fg, bg = Colours.purple },
		["@keyword.repeat"] = { link = "Repeat" },
		Search = { fg = Colours.green, bg = Colours.cyan },
		CurSearch = { link = "Search" },
		QuickFixLine = { link = "Search" },
		Substitute = { link = "Search" },
		SignColumn = { fg = Colours.fg, bg = Colours.bgdark },
		CursorLineSign = { link = "SignColumn" },
		Special = { fg = Colours.green },
		Debug = { link = "Special" },
		LazySpecial = { link = "Special" },
		SpecialChar = { link = "Special" },
		SpecialComment = { link = "Special" },
		Tag = { link = "Special" },
		TelescopeMatching = { link = "Special" },
		TelescopePreviewMatch = { link = "Special" },
		TelescopeResultsClass = { link = "Special" },
		TelescopeResultsFileIcon = { link = "Special" },
		["@constant.builtin"] = { link = "Special" },
		["@constructor"] = { link = "Special" },
		["@string.regexp"] = { link = "Special" },
		["@string.special"] = { link = "Special" },
		["@character.special"] = { link = "SpecialChar" },
		SpecialKey = { fg = Colours.purple },
		SpellBad = { fg = Colours.red, bg = "none", bold = opts.allowTextStyling, underline = opts.allowTextStyling },
		SpellCap = { fg = Colours.green, bg = Colours.bgdark, underline = opts.allowTextStyling },
		SpellLocal = { fg = Colours.purple, bg = Colours.bgdark, underline = opts.allowTextStyling },
		SpellRare = { fg = Colours.yellow, bg = Colours.bgdark, underline = opts.allowTextStyling },
		Statement = { fg = Colours.green, bold = opts.allowTextStyling },
		Conditional = { link = "Statement" },
		Exception = { link = "Statement" },
		Keyword = { fg = Colours.fg },
		Label = { link = "Statement" },
		Repeat = { link = "Statement" },
		helpHyperTextEntry = { link = "Statement" },
		phpDefine = { link = "Statement" },
		rubyDefine = { link = "Statement" },
		["@markup.checked"] = { link = "Statement" },
		["@markup.list"] = { link = "Statement" },
		["@markup.unchecked"] = { link = "Statement" },
		StatusLine = { fg = Colours.purple, bg = Colours.fg, bold = opts.allowTextStyling },
		MsgSeparator = { link = "StatusLine" },
		StatusLineNC = { fg = Colours.fg, bg = Colours.fg, bold = opts.allowTextStyling },
		String = { fg = Colours.purple },
		CtrlPMatch = { link = "String" },
		NERDTreeExecFile = { link = "String" },
		NvimString = { link = "String" },
		TelescopePreviewDirectory = { link = "String" },
		helpExample = { link = "String" },
		markdownCodeBlock = { link = "String" },
		phpHereDoc = { link = "String" },
		["@markup.quote"] = { link = "String" },
		["@string"] = { link = "String" },
		SyntasticErrorSign = { fg = Colours.yellow },
		SyntasticWarningSign = { fg = Colours.purple },
		TabLine = { fg = Colours.fg, bg = Colours.bgdark },
		TabLineFill = { fg = Colours.green, bg = Colours.bgdark },
		TabLineSel = { fg = Colours.yellow, bg = Colours.bgdark, bold = opts.allowTextStyling },
		TabLineSelSep = { fg = Colours.purple, bg = Colours.bgdark, bold = opts.allowTextStyling },
		TabLineSep = { fg = Colours.fg, bg = Colours.bgdark },
		["@tag"] = { link = "Tag" },
		["@tag.builtin"] = { link = "Tag" },
		TelescopeBorder = { fg = Colours.purple, bg = Colours.bgdark },
		TelescopePreviewBorder = { link = "TelescopeBorder" },
		TelescopePromptCounter = { link = "TelescopeBorder" },
		TelescopeResultsBorder = { link = "TelescopeBorder" },
		TelescopeMultiIcon = {},
		TelescopeMultiSelection = {},
		TelescopeNormal = { bg = Colours.bgdark },
		TelescopePreviewBlock = {},
		TelescopePreviewCharDev = {},
		TelescopePreviewDate = {},
		TelescopePreviewExecute = {},
		TelescopePreviewGroup = {},
		TelescopePreviewHyphen = {},
		TelescopePreviewLink = {},
		TelescopePreviewMessage = { fg = Colours.green, bold = opts.allowTextStyling },
		TelescopePreviewMessageFillchar = {},
		TelescopePreviewNormal = { bg = Colours.bgdark },
		TelescopePreviewPipe = {},
		TelescopePreviewRead = {},
		TelescopePreviewSize = {},
		TelescopePreviewSocket = {},
		TelescopePreviewSticky = {},
		TelescopePreviewUser = {},
		TelescopePreviewWrite = {},
		TelescopePromptBorder = { fg = Colours.yellow, bg = Colours.bg },
		TelescopePromptNormal = { bg = Colours.bgdark },
		TelescopeResultsComment = {},
		TelescopeResultsDiffUntracked = {},
		TelescopeResultsField = {},
		TelescopeResultsNormal = { bg = Colours.bgdark },
		TelescopeResultsNumber = {},
		TelescopeResultsSpecialComment = {},
		TelescopeSelection = { bg = Colours.bg },
		TelescopePreviewLine = { link = "TelescopeSelection" },
		TelescopeSelectionCaret = { fg = Colours.green, bg = Colours.bg, bold = opts.allowTextStyling },
		TelescopeTitle = { fg = Colours.green, bg = Colours.bgdark },
		TelescopePreviewTitle = { link = "TelescopeTitle" },
		TelescopePromptPrefix = { link = "TelescopeTitle" },
		TelescopePromptTitle = { link = "TelescopeTitle" },
		TelescopeResultsTitle = { link = "TelescopeTitle" },
		TermCursor = { reverse = true },
		Title = { fg = Colours.yellow, bold = opts.allowTextStyling },
		FloatTitle = { link = "Title" },
		helpHeadline = { link = "Title" },
		["@markup.heading"] = { link = "Title" },
		["@markup.heading.1"] = { link = "Title" },
		["@markup.heading.2"] = { link = "Title" },
		["@markup.heading.3"] = { link = "Title" },
		["@markup.heading.4"] = { link = "Title" },
		["@markup.heading.5"] = { link = "Title" },
		["@markup.heading.6"] = { link = "Title" },
		["@text.title"] = { link = "Title" },
		Todo = { fg = Colours.cyan, bold = opts.allowTextStyling, underline = opts.allowTextStyling },
		["@comment.todo"] = { link = "Todo" },
		["@text.todo"] = { link = "Todo" },
		TroubleFsBasename = { fg = Colours.fg, bg = "none" },
		TroubleFsCount = { fg = Colours.fg, bg = "none" },
		TroubleFsFilename = { fg = Colours.fg, bg = "none" },
		TroubleFsSource = { fg = Colours.fg, bg = "none" },
		TroubleIconArray = { bg = "none" },
		TroubleIconBoolean = { bg = "none" },
		TroubleIconClass = { bg = "none" },
		TroubleIconConstant = { bg = "none" },
		TroubleIconConstructor = { bg = "none" },
		TroubleIconFunction = { bg = "none" },
		TroubleIconNamespace = { bg = "none" },
		TroubleIconNull = { bg = "none" },
		TroubleIconNumber = { bg = "none" },
		TroubleIconObject = { bg = "none" },
		TroubleIconOperator = { fg = Colours.yellow, bg = "none" },
		TroubleIndentFoldClosed = { fg = Colours.yellow, bg = "none" },
		TroubleIndentFoldOpen = { fg = Colours.yellow, bg = "none" },
		TroubleIndentLast = { fg = Colours.yellow, bg = "none" },
		TroubleIndentMiddle = { fg = Colours.yellow, bg = "none" },
		TroubleIndentTop = { fg = Colours.yellow, bg = "none" },
		TroubleIndentWs = { fg = Colours.fg, bg = "none" },
		TroubleNormal = { fg = Colours.fg, bg = "none" },
		TroubleNormalNC = { fg = Colours.fg, bg = "none" },
		TroublePos = { fg = Colours.fg, bg = "none" },
		TroublePreview = { fg = Colours.fg, bg = "none" },
		Type = { fg = Colours.green, bold = opts.allowTextStyling },
		NvimNumberPrefix = { link = "Type" },
		NvimOptionSigil = { link = "Type" },
		StorageClass = { link = "Type" },
		Structure = { link = "Type" },
		Typedef = { link = "Type" },
		["@function.builtin"] = { link = "Type" },
		["@lsp.type.type"] = { link = "Type" },
		["@type"] = { link = "Type" },
		["@module"] = { link = "Typedef" },
		["@module.builtin"] = { link = "Typedef" },
		["@type.builtin"] = { link = "Typedef" },
		["@type.definition"] = { link = "Typedef" },
		Underlined = { fg = Colours.purple, underline = opts.allowTextStyling },
		helpHyperTextJump = { link = "Underlined" },
		helpURL = { link = "Underlined" },
		htmlLink = { link = "Underlined" },
		["@markup.link"] = { link = "Underlined" },
		["@markup.link.label"] = { link = "Underlined" },
		["@markup.link.url"] = { link = "Underlined" },
		["@string.special.url"] = { link = "Underlined" },
		["@text.underline"] = { link = "Underlined" },
		["@text.uri"] = { link = "Underlined" },
		User = { fg = Colours.green, bg = Colours.purple },
		VertSplit = { link = "Normal" },
		WinSeparator = { link = "VertSplit" },
		Visual = { fg = Colours.yellow, bg = Colours.cyan },
		BlinkCmpDocCursorLine = { link = "Visual" },
		WarningMsg = { fg = Colours.yellow },
		["@comment.warning"] = { link = "WarningMsg" },
		WhichKey = { bg = Colours.bgdark },
		WhichKeyBorder = { bg = Colours.bgdark },
		WhichKeyDesc = { fg = Colours.green, bg = "none" },
		WhichKeyFloat = { bg = Colours.bgdark },
		WhichKeyGroup = { fg = Colours.fg, bg = Colours.bgdark },
		WhichKeySeparator = { fg = Colours.purple, bg = "none" },
		WhichKeyValue = { fg = Colours.yellow, bg = "none" },
		WildMenu = { fg = Colours.fg, bg = Colours.bgdark },
		WinBar = { bold = opts.allowTextStyling },
		WinBarNC = { link = "WinBar" },
		gitCommitBranch = { fg = Colours.yellow },
		gitCommitSelectedFile = { fg = Colours.green },
		gitCommitSelectedType = { fg = Colours.green },
		gitCommitUnmergedFile = { fg = Colours.purple },
		gitCommitDiscardedFile = { link = "gitCommitUnmergedFile" },
		gitCommitUntrackedFile = { link = "gitCommitUnmergedFile" },
		gitCommitUnmergedType = { fg = Colours.purple },
		gitCommitDiscardedType = { link = "gitCommitUnmergedType" },
		htmlArg = { fg = Colours.green },
		htmlBold = { bold = opts.allowTextStyling },
		htmlBoldItalic = { bold = opts.allowTextStyling, underline = opts.allowTextStyling },
		htmlBoldUnderline = { bold = opts.allowTextStyling, underline = opts.allowTextStyling },
		htmlBoldUnderlineItalic = { bold = opts.allowTextStyling, underline = opts.allowTextStyling },
		htmlH1 = { bold = opts.allowTextStyling },
		htmlItalic = { underline = opts.allowTextStyling },
		htmlTag = { fg = Colours.green },
		htmlEndTag = { link = "htmlTag" },
		htmlTagName = { fg = Colours.green },
		htmlUnderline = { underline = opts.allowTextStyling },
		htmlUnderlineItalic = { underline = opts.allowTextStyling },
		lCursor = { reverse = true },
		lessVariable = { fg = Colours.yellow },
		markdownBold = { bold = opts.allowTextStyling },
		markdownItalic = { underline = opts.allowTextStyling },
		mustacheMarker = { fg = Colours.purple },
		mustachePartial = { fg = Colours.purple },
		mustacheSection = { bold = opts.allowTextStyling },
		mustacheVariable = { fg = Colours.yellow },
		mustacheVariableUnescape = { fg = Colours.purple },
		netrwClassify = { fg = Colours.fg, bold = opts.allowTextStyling },
		netrwExe = { fg = Colours.purple },
		phpIdentifier = { fg = Colours.yellow },
		phpVarSelector = { link = "phpIdentifier" },
		phpSpecialFunction = { fg = Colours.purple },
		shDerefSimple = { fg = Colours.yellow },
		shDerefVar = { link = "shDerefSimple" },
		xmlTag = { fg = Colours.green },
		xmlAttrib = { link = "xmlTag" },
		xmlEndTag = { link = "xmlTag" },
		xmlEqual = { link = "xmlTag" },
		xmlTagName = { fg = Colours.purple },
		xmlString = { link = "xmlTagName" },
		["@comment.documentation"] = { fg = Colours.cyan },
		["@comment.note"] = { fg = Colours.pink, bold = opts.allowTextStyling },
		["@lsp.type.property"] = { fg = Colours.green },
		["@markup.italic"] = { italic = opts.allowTextStyling },
		["@markup.strikethrough"] = { strikethrough = opts.allowTextStyling },
		["@markup.strong"] = { bold = opts.allowTextStyling },
		["@markup.underline"] = { underline = opts.allowTextStyling },
		TelescopeResultsMethod = { link = "@method" },
		["@property"] = { fg = Colours.yellow },
		TelescopeResultsVariable = { link = "@property" },
		["@variable.member"] = { fg = Colours.yellow },
	}
	if opts.transparent then
		theme["Normal"].bg = "none"
		theme["StatusLine"].bg = "none"
	end
	if opts.overrides ~= false then
		theme = vim.tbl_deep_extend("force", theme, opts.overrides)
	end
	return theme
end
return Highlights
