vim.api.nvim_create_user_command("Zigrun", function()
	local filename = vim.api.nvim_buf_get_name(0)
	vim.cmd("w")
	print(vim.fn.system({ "zig", "run", filename }))
end, { desc = "Run the current Zig buffer" })

vim.api.nvim_create_user_command("Zigbuild", function()
	vim.cmd("w")
	print(vim.fn.system({ "zig", "build" }))
end, { desc = "Compile the Zig project" })

vim.api.nvim_create_user_command("Zigtest", function()
	local filename = vim.api.nvim_buf_get_name(0)
	vim.cmd("w")
	print(vim.fn.system({ "zig", "test", filename }))
end, { desc = "Test the current Zig buffer" })

vim.keymap.set({ "n" }, "<leader>lr", function()
	vim.cmd("Zigrun")
end, { desc = "Zig Run" })
vim.keymap.set({ "n" }, "<leader>lc", function()
	vim.cmd("Zigbuild")
end, { desc = "Zig Build" })
vim.keymap.set({ "n" }, "<leader>lt", function()
	vim.cmd("Zigtest")
end, { desc = "Zig Test" })
